<a href="https://colab.research.google.com/github/LuuQuangHoi/AI_Exercise_W8_ML_ANN/blob/main/Perceptron_Crabs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import matplotlib.pyplot as plt
url = '/content/crabs.csv'
data = pd.read_csv(url)

# speies B -> 0   O -> 1
# sex M -> 1   F -> 0

In [43]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Chuyen du lieu
dataReplace = data.replace(to_replace=["B","O","M","F"],value = [0,1,1,0])
data_x = dataReplace.drop(['sex'], axis=1)
data_y = dataReplace.drop(['speies','index','fontallip','rearwidth',
                           'length','width','depth'], axis=1)
# Du lieu dau vao
X = data_x.to_numpy()
y = data_y.to_numpy()
print(X)
#print(y)

[[ 0.   1.   8.1 ... 16.1 19.   7. ]
 [ 0.   2.   8.8 ... 18.1 20.8  7.4]
 [ 0.   3.   9.2 ... 19.  22.4  7.7]
 ...
 [ 1.  48.  21.9 ... 42.6 47.4 19.5]
 [ 1.  49.  22.5 ... 43.  48.7 19.8]
 [ 1.  50.  23.1 ... 46.2 52.5 21.1]]


In [52]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)   #hoc ti le
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y.T[:10])

[[ 0.97182532  0.32027127  0.85804417  0.73626177  0.7040349   0.7301595
   0.77759276]
 [ 0.97182532  0.90163889  0.94665458  0.41995445  1.02306205  0.90081448
   1.17059993]
 [ 0.97182532 -0.55178016 -0.2938912  -0.56850592 -0.3255527  -0.38566149
  -0.37119743]
 [ 0.97182532 -0.84246397  0.00147684  0.53856969 -0.16603913 -0.25438843
  -0.06888422]
 [-1.02899151  0.53828412  0.20823447 -0.01496811  0.50101763  0.58575914
   0.26366031]] [[ 1.  30.  18.5 14.6 37.  42.  16.6]
 [ 1.  38.  18.8 13.8 39.2 43.3 17.9]
 [ 1.  18.  14.6 11.3 29.9 33.5 12.8]
 [ 1.  14.  15.6 14.1 31.  34.5 13.8]
 [ 0.  33.  16.3 12.7 35.6 40.9 14.9]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [53]:
model = Perceptron(max_iter=500, eta0=0.1, random_state = 0) # epoch , toc do hoc 0 - 1 , trang thai lay giai tri ngau nhien
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
#print(y_test)
print('Do chinh xac cua mo hinh:',accuracy_score(y_test,y_pred))

[1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1
 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1]
Do chinh xac cua mo hinh: 0.95


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
